import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BCM)

gServo = GPIO.setup(5, GPIO.OUT)
gMotor = GPIO.PWM(5, 50)
#the continuous one
cServo = GPIO.setup(6, GPIO.OUT)
cMotor = GPIO.PWM(6, 50)
plServo = GPIO.setup(13, GPIO.OUT)
plMotor = GPIO.PWM(13, 50)
paServo = GPIO.setup(19, GPIO.OUT)
paMotor = GPIO.PWM(19, 50)

gMotor.start(0)
cMotor.start(0)
plMotor.start(0)
paMotor.start(0)
sleep(3)

plMotor.ChangeDutyCycle(5)
sleep(1)
paMotor.ChangeDutyCycle(5)
sleep(1)
plMotor.ChangeDutyCycle(10)
sleep(1)
paMotor.ChangeDutyCycle(10)
sleep(1)
plMotor.ChangeDutyCycle(0)
paMotor.ChangeDutyCycle(0)

cMotor.ChangeDutyCycle(5)
sleep(.1)
cMotor.ChangeDutyCycle(0)
sleep(1)
gMotor.ChangeDutyCycle(5)
sleep(1)
cMotor.ChangeDutyCycle(10)
sleep(.1)
cMotor.ChangeDutyCycle(0)
sleep(1)
gMotor.ChangeDutyCycle(10)
sleep(1)
gMotor.ChangeDutyCycle(0)
cMotor.ChangeDutyCycle(0)
plMotor.ChangeDutyCycle(0)
paMotor.ChangeDutyCycle(0)

gMotor.stop()
cMotor.stop()
plMotor.stop()
paMotor.stop()

GPIO.cleanup()
